# Generated by Django 3.2.7 on 2021-10-25 19:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.SlugField(blank=True, max_length=60)),
                ('number_of_questions', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='# of Questions')),
                ('pass_mark', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Pass Mark')),
                ('draft', models.BooleanField(blank=True, default=False, verbose_name='Draft')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.FileField(blank=True, default=None, null=True, upload_to='quiz_images/', verbose_name='Figure')),
                ('content', models.TextField(help_text='Enter the question text.', max_length=1000, verbose_name='Question')),
                ('reason', models.TextField(blank=True, help_text='Explanation for when question is answered.', max_length=2000, verbose_name='Explanation')),
                ('hasAnswer', models.BooleanField(default=False, verbose_name='Has Answer')),
                ('quiz', models.ManyToManyField(blank=True, to='MCQuizApp.Quiz', verbose_name='Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='This contains the answer', max_length=1000, verbose_name='Content')),
                ('correct', models.BooleanField(default=False, help_text='Set to this if the answer is correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MCQuizApp.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
